fix(EPMEDUTOUR-10506): a11y support
radzima-green-travel/radzima.app pull request #66
Opened 2022-09-09 06:34 UTC by error404as

### What does this PR do:
A11y fixes for language selector links (screen reader), external links (screen reader), landmark wrappers.

EPMEDUTOUR-11595: Selected language is not focused and not pronounced by screen reader
EPMEDUTOUR-11634: Users should be warned in advance if their input action will open a new window
EPMEDUTOUR-11635: All page content should be contained by landmarks

2022-09-09 08:47 UTC, mariakravchenko approved these changes

2022-09-09 14:42 UTC, AndreiShumski2 approved these changes

2022-09-09 16:41 UTC, alexeykomov requested changes
I cannot run command: `npm run server`.
It produces this error:
```
[11ty] Unexpected token u in JSON at position 0 (via SyntaxError)
[11ty]
```

2022-09-10 14:02 UTC, alexeykomov approved these changes

2022-09-10 14:02 UTC, merged